// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFO04rW8ciER6Y_YXLYmf_NdTS_8yF_hQ',
    appId: '1:642056469420:web:2e666a7c07ac679eaad809',
    messagingSenderId: '642056469420',
    projectId: 'coneapp-cffaf',
    authDomain: 'coneapp-cffaf.firebaseapp.com',
    storageBucket: 'coneapp-cffaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57LWAgo0IYWaaRlymkElyTelSlbStoXM',
    appId: '1:642056469420:android:09c697aac7dddb12aad809',
    messagingSenderId: '642056469420',
    projectId: 'coneapp-cffaf',
    storageBucket: 'coneapp-cffaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUaPavvaxKrEgGNQv_8nHWVbKcY56pac',
    appId: '1:642056469420:ios:55995b593416c3d7aad809',
    messagingSenderId: '642056469420',
    projectId: 'coneapp-cffaf',
    storageBucket: 'coneapp-cffaf.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUaPavvaxKrEgGNQv_8nHWVbKcY56pac',
    appId: '1:642056469420:ios:55995b593416c3d7aad809',
    messagingSenderId: '642056469420',
    projectId: 'coneapp-cffaf',
    storageBucket: 'coneapp-cffaf.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFO04rW8ciER6Y_YXLYmf_NdTS_8yF_hQ',
    appId: '1:642056469420:web:b003075d300afeacaad809',
    messagingSenderId: '642056469420',
    projectId: 'coneapp-cffaf',
    authDomain: 'coneapp-cffaf.firebaseapp.com',
    storageBucket: 'coneapp-cffaf.firebasestorage.app',
  );
}
